name: muldeulda
description: "ChakTone(착톤) — 퍼스널 컬러 진단 앱"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  image_picker: ^1.1.2
  qr_flutter: ^4.1.0
  google_mlkit_face_detection: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
